---
- name: Install pebble
  shell: |
    export GOPATH="{{ go_path }}"
    go get -u github.com/letsencrypt/pebble/...
    cd "$GOPATH/src/github.com/letsencrypt/pebble"
    go install ./...
  creates: '{{ go_path }}/bin/pebble'

- name: pebble systemd service definition
  template:
    src: pebble.service.j2
    dest: /etc/systemd/system/pebble.service

- name: pebble systemd service
  systemd:
    name: pebble.service
    enabled: yes
    daemon_reload: yes
    state: started
